% Intervals and labels were obtained using matlab tool: Signal Labeler

s31_s4 = Sarah37v4;  % Replace with your actual data variable

% Signal and time vectors
dt_variables = { ...
    s31_s4.RawV, ...
    s31_s4.FilteredV, ...
    s31_s4.FilteredmV, ...
};
ti = s31_s4.Time;

% Output filenames ( we needed Raw and filtered and filteredmv to determin
% which is the best choice )
file_names = { ...
    'Subject31Session04_RawV.csv', ...
    'Subject31Session04_FilteredV.csv', ...
    'Subject31Session04_FilteredmV.csv' ...
};

file_names2 = { ...
    'RawV', ...
    'FilteredV', ...
    'FilteredmV' ...
};

% Titles for each signal type
plot_titles = { ...
    'Signal Brut étiqueté', ...
    'Signal Filtré (V) étiqueté', ...
    'Signal Filtré (mV) étiqueté' ...
};

% Y axis labels for each signal type
y_labels = { ...
    'Valeur du Signal (V)', ...     
    'Valeur du Signal (V)', ...      
    'Valeur du Signal (mV)' ...      
};

% New intervals and labels
intervals = { ...
    150:2048, ...
    2101:6122, ...
    6217:9328, ...
    9318:13738, ...
    14090:16783, ...
    16916:21004, ...
    21030:24165, ...
    24429:28876, ...
    29119:31747, ...
    31769:33375, ...
    33375:33946, ...
    33951:36121, ...
    36489:39691, ...
    39730:41038, ...
    41040:41465, ...
    41685:43435, ...
    43504:47387 ...
};

labels = [ ...
    0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0 ...
];


color_label0 = [0 0.4470 0.7410];   
color_label1 = [0.8500 0.3250 0.0980]; 

for i = 1 : numel(dt_variables)
    dt = dt_variables{i};

    combinedTime = [];
    combinedData = [];
    combinedLabels = [];

    for j = 1:numel(intervals)
        idx = intervals{j};
        combinedTime = [combinedTime; ti(idx)];      %#ok<AGROW>
        combinedData = [combinedData; dt(idx)];      %#ok<AGROW>
        combinedLabels = [combinedLabels; labels(j)*ones(numel(idx),1)]; %#ok<AGROW>
    end

    % Sample index 
    sampleIndex = (1:numel(combinedData))';

    % table
    T = table(sampleIndex, combinedTime, combinedData, combinedLabels, ...
        'VariableNames', {'Sample','Time',file_names2{i},'Label'});
    writetable(T, file_names{i});

    % plot for verification ---
    figure;
    hold on;
    for j = 1:numel(intervals)
        idx = intervals{j};
        if labels(j) == 0
            plot(idx, dt(idx), 'Color', color_label0);
        else
            plot(idx, dt(idx), 'Color', color_label1);
        end
    end
    xlabel('Échantillons');
    ylabel(y_labels{i});
    title(plot_titles{i});
    legend('Class 0','Class 1','Location','best');
    hold off;

    disp(['Saved ', file_names{i}]);
end